import type { CanonicalParameter } from "./Parameter";

function parameter(
  input: Omit<CanonicalParameter, "origin">,
): CanonicalParameter {
  return { ...input, origin: "seed" };
}

/** Liste prioritaire I4 / I7. L’import des autres codes vus est hors de ce seed. */
export const PRIORITY_PARAMETERS: CanonicalParameter[] = [
  parameter({
    id: "pfoa",
    name: "PFOA",
    cas: "335-67-1",
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 10,
    aliases: [
      { source: "sandre", externalCode: "5347", label: "Acide perfluoro-octanoïque (PFOA)" },
      { source: "sise", externalCode: "PFOA", label: "PFOA" },
      { source: "cas", externalCode: "335-67-1", label: "PFOA" },
    ],
  }),
  parameter({
    id: "pfos",
    name: "PFOS",
    cas: "1763-23-1",
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 11,
    aliases: [
      { source: "sandre", externalCode: "6561", label: "Acide sulfonique de perfluorooctane (PFOS)" },
      { source: "sise", externalCode: "PFOS", label: "PFOS" },
      { source: "cas", externalCode: "1763-23-1", label: "PFOS" },
    ],
  }),
  parameter({
    id: "pfas20",
    name: "Somme PFAS-20",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 12,
    aliases: [
      { source: "sandre", externalCode: "8847", label: "Somme de 20 substances perfluoroalkylées (PFAS)" },
      { source: "sise", externalCode: "SPFAS", label: "Somme PFAS-20" },
    ],
  }),
  parameter({
    id: "pfba",
    name: "PFBA",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 13,
    aliases: [
      { source: "sandre", externalCode: "5980", label: "Acide perfluorobutanoïque (PFBA)" },
    ],
  }),
  parameter({
    id: "pfpea",
    name: "PFPeA",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 14,
    aliases: [
      { source: "sandre", externalCode: "5979", label: "Acide perfluoropentanoïque (PFPEA)" },
    ],
  }),
  parameter({
    id: "pfhxa",
    name: "PFHxA",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 15,
    aliases: [
      { source: "sandre", externalCode: "5978", label: "Acide perfluorohexanoïque (PFHXA)" },
    ],
  }),
  parameter({
    id: "pfhpa",
    name: "PFHpA",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 16,
    aliases: [
      { source: "sandre", externalCode: "5977", label: "Acide perfluoroheptanoïque (PFHPA)" },
    ],
  }),
  parameter({
    id: "pfna",
    name: "PFNA",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 17,
    aliases: [
      { source: "sandre", externalCode: "6508", label: "Acide perfluoro-nonanoïque (PFNA)" },
    ],
  }),
  parameter({
    id: "pfda",
    name: "PFDA",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 18,
    aliases: [
      { source: "sandre", externalCode: "6509", label: "Acide perfluoro-decanoïque (PFDA)" },
    ],
  }),
  parameter({
    id: "pfuna",
    name: "PFUnDA",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 19,
    aliases: [
      { source: "sandre", externalCode: "6510", label: "Acide perfluoro undecanoïque (PFUnA)" },
    ],
  }),
  parameter({
    id: "pfdoda",
    name: "PFDoDA",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 22,
    aliases: [
      { source: "sandre", externalCode: "6507", label: "Acide perfluorododécanoique (PFDoDA)" },
    ],
  }),
  parameter({
    id: "pftrda",
    name: "PFTrDA",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 23,
    aliases: [
      { source: "sandre", externalCode: "6549", label: "Acide perfluoro tridecanoique (PFTrDA)" },
    ],
  }),
  parameter({
    id: "pfbs",
    name: "PFBS",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 24,
    aliases: [
      { source: "sandre", externalCode: "6025", label: "Acide sulfonique de perfluorobutane (PFBS)" },
    ],
  }),
  parameter({
    id: "pfhxs",
    name: "PFHxS",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 25,
    aliases: [
      { source: "sandre", externalCode: "6830", label: "Perfluorohexane sulfonate (PFHXS)" },
    ],
  }),
  parameter({
    id: "pfhps",
    name: "PFHpS",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 26,
    aliases: [
      { source: "sandre", externalCode: "6542", label: "Acide perfluoroheptane sulfonique (PFHpS)" },
    ],
  }),
  parameter({
    id: "pfds",
    name: "PFDS",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 27,
    aliases: [
      { source: "sandre", externalCode: "6550", label: "Acide perfluorodecane sulfonique (PFDS)" },
    ],
  }),
  parameter({
    id: "pfps",
    name: "PFPS",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 28,
    aliases: [
      { source: "sandre", externalCode: "8738", label: "Acide perfluoropentane sulfonique (PFPS)" },
    ],
  }),
  parameter({
    id: "pfns",
    name: "PFNS",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 29,
    aliases: [
      { source: "sandre", externalCode: "8739", label: "Acide perfluorononane sulfonique (PFNS)" },
    ],
  }),
  parameter({
    id: "pfunds",
    name: "PFUnDS",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 30,
    aliases: [
      { source: "sandre", externalCode: "8740", label: "Acide perfluoro undecane sulfonique (PFUnDS)" },
    ],
  }),
  parameter({
    id: "pfdods",
    name: "PFDoDS",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 31,
    aliases: [
      { source: "sandre", externalCode: "8741", label: "Acide perfluorododécane sulfonique (PFDoDS)" },
    ],
  }),
  parameter({
    id: "pftrds",
    name: "PFTrDS",
    cas: null,
    category: "pfas",
    canonicalUnit: "µg/L",
    displayPriority: 32,
    aliases: [
      { source: "sandre", externalCode: "8742", label: "Acide perfluoro tridecane sulfonique (PFTrDS)" },
    ],
  }),
  parameter({
    id: "nitrates",
    name: "Nitrates",
    cas: "14797-55-8",
    category: "nutrients",
    canonicalUnit: "mg/L",
    displayPriority: 20,
    aliases: [
      { source: "sandre", externalCode: "1340", label: "Nitrates (en NO3)" },
      { source: "sise", externalCode: "NO3", label: "Nitrates" },
      { source: "cas", externalCode: "14797-55-8", label: "Nitrates" },
    ],
  }),
  parameter({
    id: "nitrites",
    name: "Nitrites",
    cas: "14797-65-0",
    category: "nutrients",
    canonicalUnit: "mg/L",
    displayPriority: 21,
    aliases: [
      { source: "sandre", externalCode: "1339", label: "Nitrites (en NO2)" },
      { source: "sise", externalCode: "NO2", label: "Nitrites" },
      { source: "cas", externalCode: "14797-65-0", label: "Nitrites" },
    ],
  }),
  parameter({
    id: "lead",
    name: "Plomb",
    cas: "7439-92-1",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 30,
    aliases: [
      { source: "sandre", externalCode: "1382", label: "Plomb" },
      { source: "sise", externalCode: "PB", label: "Plomb" },
      { source: "cas", externalCode: "7439-92-1", label: "Plomb" },
    ],
  }),
  parameter({
    id: "arsenic",
    name: "Arsenic",
    cas: "7440-38-2",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 31,
    aliases: [
      { source: "sandre", externalCode: "1369", label: "Arsenic" },
      { source: "sise", externalCode: "AS", label: "Arsenic" },
      { source: "cas", externalCode: "7440-38-2", label: "Arsenic" },
    ],
  }),
  parameter({
    id: "cadmium",
    name: "Cadmium",
    cas: "7440-43-9",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 32,
    aliases: [
      { source: "sandre", externalCode: "1388", label: "Cadmium" },
      { source: "sise", externalCode: "CD", label: "Cadmium" },
    ],
  }),
  parameter({
    id: "chromium",
    name: "Chrome",
    cas: "7440-47-3",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 33,
    aliases: [
      { source: "sandre", externalCode: "1389", label: "Chrome total" },
      { source: "sise", externalCode: "CRT", label: "Chrome" },
    ],
  }),
  parameter({
    id: "nickel",
    name: "Nickel",
    cas: "7440-02-0",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 34,
    aliases: [
      { source: "sandre", externalCode: "1386", label: "Nickel" },
      { source: "sise", externalCode: "NI", label: "Nickel" },
    ],
  }),
  parameter({
    id: "copper",
    name: "Cuivre",
    cas: "7440-50-8",
    category: "metals",
    canonicalUnit: "mg/L",
    displayPriority: 35,
    aliases: [
      { source: "sandre", externalCode: "1392", label: "Cuivre" },
      { source: "sise", externalCode: "CU", label: "Cuivre" },
    ],
  }),
  parameter({
    id: "mercury",
    name: "Mercure",
    cas: "7439-97-6",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 36,
    aliases: [
      { source: "sandre", externalCode: "1387", label: "Mercure" },
      { source: "sise", externalCode: "HG", label: "Mercure" },
    ],
  }),
  parameter({
    id: "aluminium",
    name: "Aluminium",
    cas: "7429-90-5",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 37,
    aliases: [
      { source: "sandre", externalCode: "1370", label: "Aluminium total µg/l" },
      { source: "sise", externalCode: "ALTMICR", label: "Aluminium" },
      { source: "cas", externalCode: "7429-90-5", label: "Aluminium" },
    ],
  }),
  parameter({
    id: "iron",
    name: "Fer",
    cas: "7439-89-6",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 38,
    aliases: [
      { source: "sandre", externalCode: "1393", label: "Fer total" },
      { source: "sise", externalCode: "FET", label: "Fer" },
    ],
  }),
  parameter({
    id: "ecoli",
    name: "Escherichia coli",
    cas: null,
    category: "microbio",
    canonicalUnit: "n/(100mL)",
    displayPriority: 40,
    aliases: [
      { source: "sandre", externalCode: "1449", label: "Escherichia coli /100ml - MF" },
      { source: "sise", externalCode: "ECOLI", label: "Escherichia coli" },
    ],
  }),
  parameter({
    id: "enterococci",
    name: "Entérocoques",
    cas: null,
    category: "microbio",
    canonicalUnit: "n/(100mL)",
    displayPriority: 41,
    aliases: [
      { source: "sandre", externalCode: "6455", label: "Entérocoques /100ml-MS" },
      { source: "sise", externalCode: "STRF", label: "Entérocoques" },
    ],
  }),
  parameter({
    id: "atrazine",
    name: "Atrazine",
    cas: "1912-24-9",
    category: "pesticides",
    canonicalUnit: "µg/L",
    displayPriority: 50,
    aliases: [
      { source: "sandre", externalCode: "1107", label: "Atrazine" },
      { source: "sise", externalCode: "ATRZ", label: "Atrazine" },
    ],
  }),
  parameter({
    id: "pesticides_total",
    name: "Pesticides (total analysé)",
    cas: null,
    category: "pesticides",
    canonicalUnit: "µg/L",
    displayPriority: 51,
    aliases: [
      { source: "sandre", externalCode: "6276", label: "Total des pesticides analysés" },
      { source: "sise", externalCode: "PESTOT", label: "Pesticides totaux" },
    ],
  }),
  parameter({
    id: "hardness",
    name: "Titre hydrotimétrique",
    cas: null,
    category: "organoleptic",
    canonicalUnit: "°f",
    displayPriority: 80,
    aliases: [
      { source: "sandre", externalCode: "1345", label: "Titre hydrotimétrique" },
      { source: "sise", externalCode: "TH", label: "TH" },
    ],
  }),
  parameter({
    id: "ph",
    name: "pH",
    cas: null,
    category: "organoleptic",
    canonicalUnit: "unité pH",
    displayPriority: 82,
    aliases: [
      { source: "sandre", externalCode: "1302", label: "pH" },
      { source: "sise", externalCode: "PH", label: "pH" },
    ],
  }),
  parameter({
    id: "fluoride",
    name: "Fluorures",
    cas: "16984-48-8",
    category: "chemicals",
    canonicalUnit: "mg/L",
    displayPriority: 60,
    aliases: [
      { source: "sandre", externalCode: "1391", label: "Fluorures" },
      { source: "sise", externalCode: "F", label: "Fluorures" },
    ],
  }),
  parameter({
    id: "boron",
    name: "Bore",
    cas: "7440-42-8",
    category: "chemicals",
    canonicalUnit: "mg/L",
    displayPriority: 61,
    aliases: [
      { source: "sandre", externalCode: "1362", label: "Bore" },
      { source: "sise", externalCode: "B", label: "Bore" },
    ],
  }),
  parameter({
    id: "selenium",
    name: "Sélénium",
    cas: "7782-49-2",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 62,
    aliases: [
      { source: "sandre", externalCode: "1385", label: "Sélénium" },
      { source: "sise", externalCode: "SE", label: "Sélénium" },
    ],
  }),
  parameter({
    id: "antimony",
    name: "Antimoine",
    cas: "7440-36-0",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 63,
    aliases: [
      { source: "sandre", externalCode: "1376", label: "Antimoine" },
      { source: "sise", externalCode: "SB", label: "Antimoine" },
    ],
  }),
  parameter({
    id: "barium",
    name: "Baryum",
    cas: "7440-39-3",
    category: "metals",
    canonicalUnit: "mg/L",
    displayPriority: 64,
    aliases: [
      { source: "sandre", externalCode: "1396", label: "Baryum" },
      { source: "sise", externalCode: "BA", label: "Baryum" },
    ],
  }),
  parameter({
    id: "manganese",
    name: "Manganèse",
    cas: "7439-96-5",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 65,
    aliases: [
      { source: "sandre", externalCode: "1394", label: "Manganèse" },
      { source: "sise", externalCode: "MN", label: "Manganèse" },
    ],
  }),
  parameter({
    id: "uranium",
    name: "Uranium",
    cas: "7440-61-1",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 66,
    aliases: [
      { source: "sandre", externalCode: "1361", label: "Uranium" },
      { source: "sise", externalCode: "U", label: "Uranium" },
    ],
  }),
  parameter({
    id: "chromium6",
    name: "Chrome VI",
    cas: "18540-29-9",
    category: "metals",
    canonicalUnit: "µg/L",
    displayPriority: 67,
    aliases: [
      { source: "sandre", externalCode: "1371", label: "Chrome hexavalent" },
      { source: "sise", externalCode: "CR6", label: "Chrome VI" },
    ],
  }),
  parameter({
    id: "cyanide",
    name: "Cyanures",
    cas: null,
    category: "chemicals",
    canonicalUnit: "µg/L",
    displayPriority: 68,
    aliases: [
      { source: "sandre", externalCode: "1390", label: "Cyanures totaux" },
      { source: "sise", externalCode: "CN", label: "Cyanures" },
    ],
  }),
  parameter({
    id: "bromate",
    name: "Bromates",
    cas: "15541-45-4",
    category: "chemicals",
    canonicalUnit: "µg/L",
    displayPriority: 69,
    aliases: [
      { source: "sandre", externalCode: "1751", label: "Bromates" },
    ],
  }),
  parameter({
    id: "ammonium",
    name: "Ammonium",
    cas: "14798-03-9",
    category: "nutrients",
    canonicalUnit: "mg/L",
    displayPriority: 70,
    aliases: [
      { source: "sandre", externalCode: "1335", label: "Ammonium" },
      { source: "sise", externalCode: "NH4", label: "Ammonium" },
    ],
  }),
  parameter({
    id: "sodium",
    name: "Sodium",
    cas: "7440-23-5",
    category: "organoleptic",
    canonicalUnit: "mg/L",
    displayPriority: 71,
    aliases: [
      { source: "sandre", externalCode: "1375", label: "Sodium" },
      { source: "sise", externalCode: "NA", label: "Sodium" },
    ],
  }),
  parameter({
    id: "chloride",
    name: "Chlorures",
    cas: "16887-00-6",
    category: "organoleptic",
    canonicalUnit: "mg/L",
    displayPriority: 72,
    aliases: [
      { source: "sandre", externalCode: "1337", label: "Chlorures" },
      { source: "sise", externalCode: "CL", label: "Chlorures" },
    ],
  }),
  parameter({
    id: "sulfate",
    name: "Sulfates",
    cas: "14808-79-8",
    category: "organoleptic",
    canonicalUnit: "mg/L",
    displayPriority: 73,
    aliases: [
      { source: "sandre", externalCode: "1338", label: "Sulfates" },
      { source: "sise", externalCode: "SO4", label: "Sulfates" },
    ],
  }),
];

export const PFAS20_ID = "pfas20";

export const PFAS20_MEMBER_IDS = PRIORITY_PARAMETERS.filter(
  (parameter) => parameter.category === "pfas" && parameter.id !== PFAS20_ID,
).map((parameter) => parameter.id);
